# https://github.com/developmentseed/how/issues/149
# ssh-keygen -m pem -t rsa -b 4096 -C AMT-Autoridade/amt -f deploy_key
version: 2
jobs:
  build:
    docker:
      - image: node:10

    working_directory: ~/repo

    environment:
      - STAGING_BRANCH: feature/updates2019
      - PRODUCTION_BRANCH: master
      - GH_REF: git@github.com:AMT-Autoridade/amt.git
      - GH_NAME: "Major"
      - GH_EMAIL: "ci@wegomajor.com"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - add_ssh_keys:
          fingerprints:
            - "79:4c:2f:1f:11:1a:27:21:bd:05:6b:ca:80:a3:e7:60"

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ] || [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              yarn build
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to GH Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              cd dist
              git init
              git config user.name "$GH_NAME"
              git config user.email "$GH_EMAIL"
              git add .
              git commit -m "CI deploy [skip ci]"
              git remote add origin $GH_REF
              git push origin --force --quiet HEAD:gh-pages
              rm -rf .git
            else
              echo "Skip deploying to Github"
            fi
      - run:
          name: Deploy to Surge
          command: |
            if [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              cp ./dist/index.html ./dist/200.html
              ./node_modules/surge/lib/cli.js --project ./dist --domain amt-staging.surge.sh
            else
              echo "Not the branch you're looking for, skipping deploy"
            fi